[versions]
spring-dependency-management = "1.1.7"

[libraries]
# Managed versions come from Spring Boot BOM
reactor-core                    = { module = "io.projectreactor:reactor-core" }
reactor-test                    = { module = "io.projectreactor:reactor-test" }

lombok                          = { module = "org.projectlombok:lombok" }
jspecify                        = { module = "org.jspecify:jspecify" }

[plugins]
spring-dependency-management = { id = "io.spring.dependency-management",    version.ref = "spring-dependency-management" }
